providers = ["node", "php"]

[phases.setup]
apt_packages = ["git"]

[phases.install]
cmds = [
  "cd sistem-terra && npm install",
  "cd sistem-terra && composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "cd sistem-terra && npm run build --production"
]

[start]
cmd = "cd sistem-terra && chmod +x start.sh && ./start.sh"